"""
Microsoft Purview eDiscovery - Copilot & Agent Adoption Recommendation
"""
from Core.new_recommendation import new_recommendation
from Core.friendly_names import get_friendly_sku_name

async def get_recommendation(sku_name, status="Success", client=None, purview_client=None):
    """
    Purview eDiscovery provides legal hold and content search
    including Copilot interactions for litigation and investigations.
    """
    feature_name = "Microsoft Purview eDiscovery"
    friendly_sku = get_friendly_sku_name(sku_name)
    
    if status == "Success":
        license_rec = new_recommendation(
            service="Purview",
            feature=feature_name,
            observation=f"{feature_name} is active in {friendly_sku}, enabling legal hold and eDiscovery of data including Copilot interactions",
            recommendation="",
            link_text="Legal Discovery for AI Content",
            link_url="https://learn.microsoft.com/purview/ediscovery/",
            status=status
        )
    else:
        license_rec = new_recommendation(
            service="Purview",
            feature=feature_name,
            observation=f"{feature_name} is {status} in {friendly_sku}, limiting legal discovery capabilities for AI interactions",
            recommendation=f"Enable {feature_name} to preserve, search, and export content for legal matters including Copilot interactions and AI-generated content. eDiscovery allows legal teams to place holds on mailboxes containing relevant Copilot conversations, search for specific AI-generated summaries or recommendations, and produce audit logs showing what content Copilot accessed during the relevant timeframe. Critical for organizations facing litigation where AI-assisted work product may be subject to discovery requests, ensuring compliance with legal obligations while using Copilot.",
            link_text="Legal Discovery for AI Content",
            link_url="https://learn.microsoft.com/purview/ediscovery/",
            priority="Medium",
            status=status
        )
    
    # Check deployment status from PowerShell data
    deployment_recs = []
    if status == "Success" and purview_client and hasattr(purview_client, 'ediscovery_cases'):
        ediscovery_data = purview_client.ediscovery_cases
        
        if ediscovery_data.get('available'):
            total_cases = ediscovery_data.get('total_cases', 0)
            active_cases = ediscovery_data.get('active_cases', 0)
            cases = ediscovery_data.get('cases', [])
            
            if total_cases > 0:
                case_names = ', '.join([c.get('Name', 'Unnamed') for c in cases[:2]])
                if len(cases) > 2:
                    case_names += f" (+{len(cases)-2} more)"
                
                deployment_rec = new_recommendation(
                    service="Purview",
                    feature=f"{feature_name} - Case Status",
                    observation=f"{total_cases} eDiscovery cases configured ({active_cases} active): {case_names}",
                    recommendation=f"For Copilot-related legal matters, ensure eDiscovery searches include: 1) Copilot conversation logs (audit events: CopilotInteraction, PromptSubmitted), 2) Documents accessed/generated by Copilot (content search with AI activity filter), 3) Meeting transcripts where Copilot was used, 4) Email drafts created with Copilot assistance. Place legal holds on custodian mailboxes to preserve Copilot usage data. Test: create case > add data source > search 'Copilot' to verify collection. Currently {active_cases} active cases.",
                    link_text="eDiscovery Best Practices",
                    link_url="https://learn.microsoft.com/purview/ediscovery-standard",
                    priority="Low",
                    status="Success"
                )
                deployment_recs.append(deployment_rec)
            else:
                deployment_rec = new_recommendation(
                    service="Purview",
                    feature=f"{feature_name} - Readiness",
                    observation="No eDiscovery cases currently active - ensure readiness for Copilot-related legal matters",
                    recommendation="Prepare eDiscovery capability for Copilot before legal need arises: 1) Document procedures for collecting Copilot interaction logs, 2) Train legal/IT teams on searching AI-generated content, 3) Test case creation and data collection workflow, 4) Identify custodian mailboxes where Copilot usage is relevant to business areas at legal risk. When litigation occurs, Copilot conversation histories and AI-accessed documents may be discoverable - having established processes prevents delays and ensures compliance with discovery obligations.",
                    link_text="eDiscovery Planning",
                    link_url="https://learn.microsoft.com/purview/ediscovery-plan",
                    priority="Low",
                    status="Success"
                )
                deployment_recs.append(deployment_rec)
    
    if deployment_recs:
        return [license_rec] + deployment_recs
    
    return [license_rec]
